---
- name: Create mbs-manager container images
  import_tasks: create-images.yml

- name: Setup the Mincraft server instance
  import_tasks: setup-server.yml

- name: Setup Mincraft server automated backups
  import_tasks: backups.yml
